- CONTRIBUTORS.md
- package-lock.json
- yarn.lock
Adding my name, Github and Discord username :) Glad to be part of this project!!
> Add RyanV to contributors' list

- CONTRIBUTORS.md
> name added to contributors.md

- CONTRIBUTORS.md
Added my name to the CONTRIBUTORS.md
Please let me in.
Thanks. :)
> Added BiswaViraj to CONTRIBUTORS.md

- CONTRIBUTORS.md
Just starting to contribute :raised_hands:
> Add Lincon Kusunoki as contributor

- src/Components/Custom-Button/custom-button.component.jsx
> custom button

- CONTRIBUTING.md
Corrected grammar mistake in CONTRIBUTING.md
From 'waiting' to 'wasting'
> Changed grammar from 'waiting' to 'wasting'

- src/Components/Custom-Button/custom-button.component.jsx
- src/Components/Custom-Button/index.js
- src/Components/Loader/Loader.component.jsx
- src/Components/Loader/index.js
> Implemented loader spinner component

- CONTRIBUTORS.md
added my name to the contributor.md file
> Added my name to contributor file 

- CONTRIBUTORS.md
I have been working on the backend of the app and looking forward to learning the react and react-native https://play.google.com/store/apps/details?id=com.clavictor.clavimatebeta&hl=en
> Hey hi i want to contribute to the project 

- README.md
- project.json
> Add rvvergara as QA/Test Lead

- CONTRIBUTORS.md
I added my name to the list of contributors.
> Edit: Add my name to the list of contributors

- src/Components/DrumPad/index.js
- src/pages/index.js
Fix playNote, first note was't played in first time and playing previous note.
> Allow change number of beats

- package.json
- src/Components/Custom-Button/index.js
I've added the style but had to do the testing outside the App because I was getting an error while trying to import the custombutton element.
> Added styling to button component

- CONTRIBUTORS.md
Hello everyone. I have  skills of all the technologies mentioned in the project. I am good in backend using express and nodejs server.
> Adding my name to CONTIBUTERS.MD

- README.md
- project.json
> added my name to leads

- package-lock.json
- package.json
- src/Components/PlayPauseButton/PlayPauseButton.story.js
- src/Components/PlayPauseButton/index.js
1. Added PlayPause Button
2. Added Storybook for PlayPauseButton
> Added PlayPauseButton Component and storybook for it

- README.md
- project.json
@rgavinc just leaving this comment to clarify i made the correct changes?
> added myself to README + project.json

- CONTRIBUTORS.md
>  added my name

- README.md
> Readmetypos

- CONTRIBUTORS.md
Hey guys! Could you please let me in? Thanks
> added myself to contributors.md

- .eslintignore
- .travis.yml
- package-lock.json
- package.json
- src/Components/DrumLoopTile/index.js
- src/Components/DrumPad/index.js
- src/Components/Error/index.js
- src/Components/ErrorBoundary/index.js
- src/Components/FormWrapper/index.js
- src/Components/TimeSignature/timeSignature.js
- src/pages/index.js
- src/pages/signin.js
1. Added `.travis.yml`
2. Added several npm scripts for linting and ci
3. Resolved existing linting problems and added `serviceWorker.js` into `.eslintignore`
Note: the Travis CI setup is not completed yet. Need to further test or changes when the Travis permission is open.
> Setup Travis CI and fixed existing linting problems

- CONTRIBUTORS.md
hi I am adrian (frenchy on discord and I would like to join the project)
> adding my name to contributors.md

- CONTRIBUTORS.md
Add myself to the contribution list
> Add myself to the contribution list

- CONTRIBUTORS.md
I have added my name to the list of contributors.
> I have added my name to the list of contributors.

- CONTRIBUTORS.md
I would love to contribute to the React and Testing part.
> adding account info to contributors

- CONTRIBUTORS.md
Add xoxwgys56 into CONTRIBUTORS.md file
I make new pull request.
> Add xoxwgys56 to Contributor list

- CONTRIBUTORS.md
> I added my name to the contributor list 

- CONTRIBUTORS.md
Hi, I am NesonPunch and am new to this project.
> Add myself as contributor to project

- CONTRIBUTORS.md
Added name to contributors list for 1st PR. Gain access to Trello.
> Update CONTRIBUTORS.md / Access Request

- CONTRIBUTORS.md
- README.md
Adding name to CONTRIBUTORS.md and further README.md changes.  @Neha
> Adding name to CONTRIBUTORS.md and further README.md changes

- CONTRIBUTORS.md
I would like to contribute on React FrontEnd.
Currently working on Antd React project in my company and also learning react to become proficient.
> Want to Contribute on FrontEnd

- CONTRIBUTORS.md
Added my name to the contributors' list. Excited to contribute to this project. Shout out to @joshtru @yashShelatkar @zbc @aneesh4995..
> Name added to contributors list

- CONTRIBUTORS.md
Adding myself to the contributors list
> Adding myself to the contributors list

- CONTRIBUTORS.md
- src/Components/SplashScreen/SplashScreen.styles.js
- src/Components/SplashScreen/index.js
Hello, I have created responsive loading component with pulsing logo, but was not sure how exactly it is going to be used, so I just used white color as a background for container
> Create loading component

- CONTRIBUTORS.md
Hey! Added my name to the contributor's list.  :)
> Added my name to the contributor's list.

- CONTRIBUTORS.md
added my name to the contribution file. Ready to contribute to this repository.
> added my name to contribute to repository
